//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCoursesMobile.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoursePeople
    {
        public int IDCourse { get; set; }
        public int IDPeople { get; set; }
        public string RegistrationNum { get; set; }
        public virtual Course Course { get; set; }
        public virtual People People { get; set; }
    }
}
